sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arediez/docker3 -f Dockerfile.dev .

script:
  - docker run -e CI=true arediez/docker3 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker'
  env: 'Docker-env'
  bucket: 'elasticbeanstalk-ap-southeast-1-592656473699'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
